basePath: /api/v1
definitions:
  web.RegisterUserInput:
    properties:
      address_line:
        type: string
      email:
        type: string
      fullname:
        type: string
      password:
        type: string
      phone_number:
        type: string
      username:
        type: string
    required:
    - email
    - fullname
    - password
    - phone_number
    - username
    type: object
  web.RegisterUserOutput:
    properties:
      email:
        type: string
      id:
        type: integer
      username:
        type: string
    type: object
  web.WithDataResp:
    properties:
      data:
        type: any
      message:
        type: string
      status:
        type: string
    type: object
info:
  contact:
    email: riidloa@gmail.com
    name: Developer
  description: API which provide you backend service for your minimalist ecommerce
    app
  title: Anya Day API
  version: "2.0"
paths:
  /user:
    post:
      description: add new user
      parameters:
      - description: User registration data. All required except address line
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/web.RegisterUserInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/web.WithDataResp'
            - properties:
                data:
                  $ref: '#/definitions/web.RegisterUserOutput'
              type: object
      summary: add new user
      tags:
      - User
swagger: "2.0"
